### ISSUE TITLE
Create a container from your image and test it locally

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankingSystem#21]
**As** a developer
**I need** to create a container from the Dockerfile
**So that** I can prepare for the cloud portability

**Comment by np1535** [comment]
Is this a duplicate? We already have code that builds a docker container from a docker file.

**Comment by np1535** [comment]
Checked the build with the docker file; it works on bluemix too. Marking this as a duplicate of #19
