### ISSUE TITLE
balance format - double, larger or equal than 0 & TDD & BDD

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankingSystem#55]
As a Banker
I need a way to limit balance format
So that I can avoid putting invalid accounts into the system

Acceptance Criteria:
- Valid integer for both integer part and decimal part, larger or equal than 0
- at most 2 decimal
- integer part, 3 digit 1 comma
- If the input could be transfered to valid format, the system will automatically adjust its format.

Some examples:
20124 ->20,124.00
23.0 -> 23.00
-3 -> deny
8.932 -> deny

**Comment by samuelsmithhk** [comment]
It seems odd to me that we'd want to put a comma into the balance, conversely should we not be stripping out commas?

**Comment by samuelsmithhk** [comment]
What I mean is, commas are a formatting choice, a style. And different countries have different ways of formatting numbers (France, for example, uses periods instead of commas). We should store the data in the rawest form possible.

**Comment by sarahhh000** [comment]
Sorry, I just saw the message. I think it is easier to read the balance number if we add the comma there, just as what banking systems do in the USA. You could store the data as just pure as you want without the comma and the decimal point, but the output format should be as guided. We could consider more international features in the future, but this time, we just try the American way.

**Comment by sarahhh000** [comment]
Hi @samuelsmithhk  , we need to coverage line 274 and 275
```
        if ',' in balance:
            balance = re.sub(',', '', balance)
```
so could you write test case for this and fix this since it is not working when I try this:
```
{
"accounttype": 2,
"active": "0",
"balance": "100,000",
"name": "Xi Xiao"
}
```

**Comment by samuelsmithhk** [comment]
Raised a bug, #75 and fixing now.
