### ISSUE TITLE
active format - true/false & TDD & BDD

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankingSystem#56]
As a Banker
I need a way to limit active format
So that I can avoid putting invalid accounts into the system

Acceptance Criteria:
- only accept true or false as boolean

**Comment by samuelsmithhk** [comment]
Further assumptions I'm going to make:

As this is a restful interface, incoming messages can only be in string format, so should accept "true" and "false" string values. For ease of access, will be case insensitive. And can also accept "t", "f" for shorthand, and "0" eqals false, "1" equals true
