### ISSUE TITLE
add account type field & TDD & BDD

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankingSystem#59]
As a Banker
I need a way to see accounts with account type: VIP, Silver member, Gold member
So that I can categorize accounts.

Acceptance Criteria:
- Add type as an optional field
- If not ordinary account, there are three vip level: Silver(1), Gold(2), Diamond(3). User could add field with number 1, 2, 3 or string case-insensitive.
- If ordinary account, this field leaves empty

**Comment by np1535** [comment]
I would suggest that there should always be an account type field. As this is not a mandatory field; the default value of the account type would be zero(0) if no account type is specified while creating an account.

**Comment by sarahhh000** [comment]
I mean this too. By optional field I mean if the user does not provide type variable, the input is still valid, and we should give a default value to it.
