### ISSUE TITLE
Query accounts with type & TDD & BDD

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankingSystem#61]
As a Banker
I need a way to see all the accounts of given type
So that I can easily keep track of certain type accounts.

Acceptance Criteria:
- When I call the URL /accounts?type=1
URL should return a list of accounts under the type of 1
- Type could be Silver(1), Gold(2), Diamond(3). User could add field with number 1, 2, 3 or string case-insensitive.

**Comment by np1535** [comment]
Completed the change. When accounts for a type are not present or an invalid account type is entered; a message is displayed to the user.
