### ISSUE TITLE
Update account type & TDD & BDD

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankingSystem#62]
As a Banker
I need a way to update accounts type
So that I can change type of given type

Acceptance Criteria:
When PUT URL /accounts, type should be updated as expected
Type could be Silver(1), Gold(2), Diamond(3). User could add field with number 1, 2, 3 or string case-insensitive.

**Comment by np1535** [comment]
Account types can be updated. This functionality was incorporated in when the accounttype attribute was added. You can verify the functionality and close this issue.
