### ISSUE TITLE
Cannot access the application on local machine

### ISSUE THREAD

**Issue by np1535** [HansiMou/nyu-devops-BankingSystem#64]
When running `vagrant up` I get an error connection refused to localhost. Which means that redis is not accessible on localhost. I see that the server.py was updated with changes for redis connection.

**Comment by HansiMou** [comment]
Try vagrant reload -provision. And can you paste the error message here?

Are the TDD and BDD working?

**Comment by np1535** [comment]
I did try vagrant reload --provision. Is the application accessible for you on your local machine for the Master branch?

When I execute docker-compose ps, I see
`vagrant_app_1     python server.py                 **Restarting**   0.0.0.0:5000->5000/tcp`

When I manually try to restart the docker containers then  I get

`redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.`

**Comment by np1535** [comment]
I think the startup sequence of the redis server should be different.
First ping and check if redis service is available
Second connect to redis service
If not then connect to localhost

**Comment by HansiMou** [comment]
It's working on my side. I pretty much copy paste the professor's code. I will take a look later.

**Comment by np1535** [comment]
Alright, I will check the professor's code once.

**Comment by np1535** [comment]
Fixed and tested.
